version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "cron"
      cronjob: "0 0 1,15 * *"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "cron"
      cronjob: "0 0 1,15 * *"
