module.exports = {
  ALGORITHM: [
    "Array",
    "String",
    "Sorting",
    "Searching",
    "Dynamic Programming",
    "Greedy",
    "Graph",
    "Backtracking",
    "Sliding Window",
    "Two Pointers",
    "Binary Search",
    "Linked List",
    "Tree",
    "Trie",
    "Stack",
    "Queue",
    "Heap",
    "Math",
    "Bit Manipulation",
    "Recursion",
    "Matrix",
    "Segment Tree",
    "Disjoint Set",
    "Topological Sorting",
    "Network Flow",
    "Game Theory",
    "Computational Geometry",
    "Hashing",
    "Divide and Conquer",
    "String Matching",
    "Bitmasking",
    "Number Theory",
    "Geometry",
    "Probability",
    "Randomized Algorithms",
    "Heuristics",
    "Approximation Algorithms",
    "String Compression"
  ],
  DATA_STRUCTURE: [
    "Array",
    "String",
    "Linked List",
    "Stack",
    "Queue",
    "Tree",
    "Binary Tree",
    "Binary Search Tree",
    "Heap",
    "Hash Table",
    "Graph",
    "Matrix",
    "Trie",
    "Segment Tree",
    "Fenwick Tree",
    "Suffix Array",
    "Disjoint Set",
    "Bloom Filter"
  ]
};