module.exports = [
  "Array",
  "String",
  "Sorting",
  "Searching",
  "Dynamic Programming",
  "Greedy",
  "Graph",
  "Backtracking",
  "Sliding Window",
  "Two Pointers",
  "Binary Search",
  "Linked List",
  "Tree",
  "Trie",
  "Stack",
  "Queue",
  "Heap",
  "Math",
  "Bit Manipulation",
  "Recursion",
  "Matrix",
  "Segment Tree",
  "Disjoint Set",
  "Search Algorithms",
  "Topological Sorting",
  "Network Flow",
  "Game Theory",
  "Computational Geometry",
];
